apiVersion: v1
kind: Service
metadata:
  name: billy-user-api
  labels:
    app: billy-user-api
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    app: billy-user-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billy-user-api
  labels:
    app: billy-user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billy-user-api
  template:
    metadata:
      labels:
        app: billy-user-api
    spec:
      containers:
      - name: billy-user-api
        image: billy-user-api