apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: billy-authentication-api
build:
  artifacts:
  - image: billy-authentication-api
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - deployment.yaml
portForward:
- resourceType: service
  resourceName: billy-authentication-api
  port: 80
  localPort: 5000
